export default {
  login: "leguich1985",
  id: 59179689,
  node_id: "MDQ6VXNlcjU5MTc5Njg5",
  avatar_url: "https://avatars.githubusercontent.com/u/59179689?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/leguich1985",
  html_url: "https://github.com/leguich1985",
  followers_url: "https://api.github.com/users/leguich1985/followers",
  following_url:
    "https://api.github.com/users/leguich1985/following{/other_user}",
  gists_url: "https://api.github.com/users/leguich1985/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/leguich1985/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/leguich1985/subscriptions",
  organizations_url: "https://api.github.com/users/leguich1985/orgs",
  repos_url: "https://api.github.com/users/leguich1985/repos",
  events_url: "https://api.github.com/users/leguich1985/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/leguich1985/received_events",
  type: "User",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 30,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: "2019-12-23T19:13:47Z",
  updated_at: "2021-06-02T14:06:04Z",
};
